sonar.projectKey=mathmust
sonar.organization=mathmust

sonar.projectName=GerezProjetCollaboratifIntegrantDemarcheCICD

# Sources
sonar.sources=back/src/main,front/src

# Tests
sonar.tests=back/src/test,front/src

# Encodage
sonar.sourceEncoding=UTF-8

#################################################
# JAVA 11 BACKEND
#################################################
sonar.java.source=11
sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

#################################################
# ANGULAR 14 FRONTEND
#################################################
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

#################################################
# Exclusions
#################################################
sonar.exclusions=**/node_modules/**,**/*.spec.ts